### ISSUE TITLE
sqlite: BEGIN IMMEDIATE/EXCLUSIVE transactions

### ISSUE THREAD

**Issue by teucer** [encode/databases#183]
I would be beneficial to allow different types of transaction for [sqlite](https://www.sqlite.org/lang_transaction.html).

**Comment by tomchristie** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
