### ISSUE TITLE
KeyError: mysql+pymysql

### ISSUE THREAD

**Issue by xujiang1** [encode/databases#191]
`Traceback (most recent call last):

  File "test.py", line 4, in <module>

database = databases.Database('mysql+pymysql://root:vipdatacenter@192.168.30.207:3306/collection_server?
charset=utf8mb4')
  
File "C:\Users\xuzhu\.virtualenvs\re-common\lib\site-packages\databases\core.py", line 65, in __init__
    backend_str = self.SUPPORTED_BACKENDS[self.url.scheme]

KeyError: 'mysql+pymysql'
`

原因为在0.3.0版本中使用了 

`backend_str = self.SUPPORTED_BACKENDS[self.url.scheme]`

而在0.2.6版本中

`backend_str = self.SUPPORTED_BACKENDS[self.url.dialect]`

dialect对string进行了分割

`    @property
    def dialect(self) -> str:
        return self.components.scheme.split("+")[0]
`

SUPPORTED_BACKENDS 为

`    SUPPORTED_BACKENDS = {

        "postgresql": "databases.backends.postgres:PostgresBackend",

        "postgresql+aiopg": "databases.backends.aiopg:AiopgBackend",

        "postgres": "databases.backends.postgres:PostgresBackend",

        "mysql": "databases.backends.mysql:MySQLBackend",

        "sqlite": "databases.backends.sqlite:SQLiteBackend",

    }`

里面只有mysql 作为键 不能使用mysql+pymysql作为键，

我感觉这里是个bug或者作者应该添加mysql+pymysql作为键

**Comment by tomchristie** [comment]
Hi there, thanks for getting involved. 😃

pymysql is not a supported driver, you should use `mysql://root:vipdatacenter@192.168.30.207:3306/collection_server` as the database URL.

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
