### ISSUE TITLE
No method for returning

### ISSUE THREAD

**Issue by kajuberdut** [encode/databases#55]
SQLAlchemy Core supports a returning clause: https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#insert-update-returning

Because database.execute returns None, and database.fetch* do not support values, it does not seem there is any way to execute and update or insert returning columns.

I can try to create a pull request for this if you can specify what the API should be. Perhaps optional values on select or database.returning(query, values).

**Comment by tomchristie** [comment]
First thing to note: `database.execute` returns the last cursor postion. (Since the latest release) 

So you can perfectly well use `update..returning` at the moment, but you'll need to use `.values()` on the query itself. So eg `fetch_all(query.values(...))` rather than `fetch_all(query, values...)`

Possible that we ought to accept values on all the API query methods - would probably accept a pull request for that.
