### ISSUE TITLE
Accessing Record values by dot notation

### ISSUE THREAD

**Issue by Spacehug** [encode/databases#73]
If I am not missing anything, is there a way to get PG Record values using dot notation instead of dict-like syntax?

For now we have to use something like `user['hashed_password']` which breaks `Readability counts.` of zen :)

Would be great to use just `user.hashed_password`.

**Comment by tomchristie** [comment]
Nope. We *probably* won't do that, because it could end up clashing with the actual API.

I expect we'd like stay with dictionary-like interfaces for records, and that higher level abstractions on top of this are the right place to start building actually objects, with attribute-lookups. https://github.com/encode/orm
